Add instructions to create a directory before running `rustup override`
intermezzOS/book pull request #167
Opened 2017-06-08 22:43 UTC by jdanford

Fix #157

2017-06-09 14:53 UTC, steveklabnik requested changes

2017-06-09 14:53 UTC, steveklabnik commented on src/installing-rust.md
> +We don't have a project directory yet, so let's create one:
So, we do this over at http://intermezzos.github.io/book/multiboot-headers.html#writing-our-own-multiboot-header

I can see why doing it here is also nicer, but we should remove that as well.

2017-06-09 17:40 UTC, jdanford commented
My bad, I figured it had to exist somewhere but I didn't look hard enough! Fixed.

2017-06-17 18:54 UTC, jdanford commented on src/installing-rust.md
> +We don't have a project directory yet, so let's create one:
This has been fixed, not sure if you saw the other comment! Hopefully force pushing wasn't the wrong way to do it.

2017-06-19 18:01 UTC, steveklabnik commented on src/installing-rust.md
> +We don't have a project directory yet, so let's create one:
It's not, it's the perfect way. Thanks a ton!

2017-06-19 18:01 UTC, steveklabnik approved these changes

2017-06-19 18:01 UTC, merged